[project]
name = "sitagaki2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "backtesting>=0.6.3",
    "catboost>=1.2.7",
    "ipykernel>=6.29.5",
    "lightgbm>=4.6.0",
    "matplotlib>=3.10.1",
    "nbformat>=5.10.4",
    "numpy==1.26.4",
    "pandas>=2.2.3",
    "pandas-ta>=0.3.14b0",
    "plotly>=5.13.1,<6.0.0",
    "polars>=1.24.0",
    "pyarrow>=19.0.1",
    "pytest>=8.3.5",
    "pyqlib>=0.9.6",
    "scikit-learn>=1.6.1",
    "seaborn>=0.13.2",
    "setuptools>=75.9.1",
    "vectorbt>=0.27.1",
    "xgboost>=3.0.0",
    "yfinance>=0.2.55",
    "pandera>=0.23.1",
    "icecream>=2.1.4",
    "ruff>=0.11.2",
]

[tool.setuptools.packages.find]
where = ["src"]     # 一応明示しておく

[tool.pytest.ini_options]
addopts = "--import-mode=importlib"

[tool.ruff]
select = ["E", "F", "W", "I", "B", "C4", "PL"]
ignore = ["PLR2004"]
